version: "3.8"

services:
  stemplayer:
    build:
      context: .
      dockerfile: dockerfile
    image: stemplayer
    ports:
      - "${API_PORT}:8000"
    volumes:
      - /tmp/asep:/tmp/asep:z
      - ${PWD}/src:/app
    command: bash -c "chmod +x /app/0.sh && bash /app/0.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # demo purposes 
  demo:
      image: dunglas/frankenphp:1.12.7-php8-alpine
      ports:
        - "${DEMO_PORT}:80"
        - "443:443"
      environment:
        SERVER_NAME: ":80"
        SERVER_ROOT: "/demo"
      volumes:
            - ${PWD}/demo:/demo
            - caddy_data:/data
            - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: